# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

default_top_img: images/site/top.jpg

avatar:
  img: images/site/avatar.jpg
  effect: false

post_meta:
  # Home Page
  page:
    date_format: relative

toc:
  number: false
  expand: true
  # Only for post
  scroll_percent: false

code_blocks:
  theme: pale night
  macStyle: true

busuanzi:
  page_pv: false

aside:
  card_author:
    description: 'SDE <a href="https://www.tencent.com" target="_blank">@Tencent</a> | B.Eng. in CS <a href="https://www.hitsz.edu.cn" target="_blank">@HITSZ</a> </br> Photographer | Otaku'
    button:
      enable: false
  card_announcement:
    content: Code is cheap. Show me your talk.
  card_archives:
    enable: false
  card_webinfo:
    enable: false

social:
  fab fa-github: https://github.com/DavidXie03 || Github
  fas fa-envelope: mailto:davidxie03@qq.com || Email
  fab fa-500px: https://500px.com.cn/davidxie03 || 500px
  fab fa-bilibili: https://space.bilibili.com/346408087 || Bilibili

# 美化页面显示
beautify:
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: '#F47466'

footer:
  owner:
    since: 2026

index_post_content:
  length: 300

post_copyright:
  enable: false

wordcount:
  enable: true

# 搜索功能
search:
  use: local_search

# 关闭分享
share:
  use:

# 阅读模式
readmode: false

inject:
  head:
    - "<style>.avatar-img img:hover { transform: none !important; }</style>"
    - "<style>.card-info-social-icons i:hover { transform: none !important; }</style>"
    - "<style>#page-header.full_page, #page-header.not-home-page, #page-header.post-bg { background-color: rgba(40, 120, 220, 0.35); background-blend-mode: overlay; }</style>"
    - "<style>#local-search .search-dialog hr { display: none; }</style>"